appender.0.type = Console
appender.0.name = CONSOLE
appender.0.layout.type = PatternLayout
appender.0.layout.pattern = %5p [%t] (%F:%L) - %m%n

appender.1.type = RollingFile
appender.1.name = EVERYTHING_LOG
appender.1.fileName = logs/everything.log
appender.1.filePattern = logs/everything.%i.log
appender.1.layout.type = PatternLayout
appender.1.layout.pattern = [%t] %d{dd-MM-yyyy HH:mm:ss} %-5p %c{1}: %m%n
appender.1.policy.type = SizeBasedTriggeringPolicy

appender.2.type = RollingFile
appender.2.name = INFO_LOG
appender.2.fileName = logs/info.log
appender.2.filePattern = logs/info.%i.log
appender.2.layout.type = PatternLayout
appender.2.layout.pattern = [%t] %d{dd-MM-yyyy HH:mm:ss} %-5p %c{1}: %m%n
appender.2.policy.type = SizeBasedTriggeringPolicy

appender.3.type = RollingFile
appender.3.name = WARN_LOG
appender.3.fileName = logs/warn.log
appender.3.filePattern = logs/warn.%i.log
appender.3.layout.type = PatternLayout
appender.3.layout.pattern = [%t] %d{dd-MM-yyyy HH:mm:ss} %-5p %c{1}: %m%n
appender.3.policy.type = SizeBasedTriggeringPolicy

appender.4.type = RollingFile
appender.4.name = ERROR_LOG
appender.4.fileName = logs/error.log
appender.4.filePattern = logs/error.%i.log
appender.4.layout.type = PatternLayout
appender.4.layout.pattern = [%t] %d{dd-MM-yyyy HH:mm:ss} %-5p %c{1}: %m%n
appender.4.policy.type = SizeBasedTriggeringPolicy

rootLogger.level = DEBUG
rootLogger.appenderRef.0.ref = CONSOLE
rootLogger.appenderRef.0.level = INFO
rootLogger.appenderRef.1.ref = EVERYTHING_LOG
rootLogger.appenderRef.1.level = DEBUG
rootLogger.appenderRef.2.ref = INFO_LOG
rootLogger.appenderRef.2.level = INFO
rootLogger.appenderRef.3.ref = WARN_LOG
rootLogger.appenderRef.3.level = WARN
rootLogger.appenderRef.4.ref = ERROR_LOG
rootLogger.appenderRef.4.level = ERROR